src/Components/init.text
src/Pages/Chat/ChatList/init.text
src/Pages/Chat/ChatRoom/init.text
src/Pages/Home/init.text
src/Pages/Login/init.text
src/Pages/Page404/init.text
src/Pages/Post/PostDetail/init.text
src/Pages/Post/PostUpload/init.text
src/Pages/Profile/EditProfile/init.text
src/Pages/Profile/Feed/init.text
src/Pages/Register/init.text
src/Pages/Search/init.text
src/Pages/SetProfile/init.text

- 생성한 폴더도 깃에 push할 수 있음
close : #4

fix: 더미파일생성

---

src/Components/button/L-Disabled-button.js
src/Components/button/L-button.js
src/Components/button/M-Activ-button.js
src/Components/button/M-Disable-button.js
src/Components/button/M-button.js
src/Components/button/Ms-Disabled-button.js
src/Components/button/Ms-button.js
src/Components/button/S-Activ-button.js
src/Components/button/S-button.js

세부 컴포넌트 생성

---

src/App.js
src/Components/HomePost.jsx

Feat: 홈포스트 컴포넌트 생성

---

src/App.js
src/Pages/Chat/ChatList/ChatList.jsx
src/Pages/Chat/ChatList/init.text
src/Pages/Chat/ChatRoom/ChatRoom.jsx
src/Pages/Chat/ChatRoom/init.text
src/Pages/Home/Home.jsx
src/Pages/Home/init.text
src/Pages/Login/Login.jsx
src/Pages/Login/init.text
src/Pages/Page404/Page404.jsx
src/Pages/Page404/init.text
src/Pages/Post/PostDetail/PostDetail.jsx
src/Pages/Post/PostDetail/init.text
src/Pages/Post/PostUpload/PostUpload.jsx
src/Pages/Post/PostUpload/init.text
src/Pages/Profile/EditProfile/EditProfile.jsx
src/Pages/Profile/EditProfile/init.text
src/Pages/Profile/Feed/Feed.jsx
src/Pages/Profile/Feed/init.text
src/Pages/Register/Register.jsx
src/Pages/Register/init.text
src/Pages/Search/Search.jsx
src/Pages/Search/init.text
src/Pages/SetProfile/SetProfile.jsx
src/Pages/SetProfile/init.text
src/Router/Router.jsx

- 페이지별 컴포넌트 생성 후 라우팅
- 각 url로 접속 시 경로에 따른 컴포넌트를 보여줌
- 각각 Page폴더에 있는 컴포넌트들을 수정하여 사용하면됨
close : #23

feat: 라우터 추가

---

src/Components/HomePost.jsx
src/Components/Product.jsx

feat: 홈포스트 추가

---

src/Components/Navbar.jsx

- 페이지별 재사용 가능한 Navbar 
- 
close : #12

feat/Navbar 컴포넌트 생성

---

src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
src/Pages/Post/PostDetail/PostDetail.jsx

- /post/postDetail url 대응 가능
- 없음
close : #39

feat: PostDetail 페이지 컴포넌트 생성

---

src/Components/button/CommonButton.jsx

- 버튼 컴포넌트 재 사용성 확장
-
close : #35

feat: button 컴포넌트 생성

---

src/Pages/SetProfile/SetProfile.jsx

feat: SetProfile 페이지 컴포넌트 생성

---

src/Pages/Post/PostDetail/PostDetail.jsx
src/Pages/Profile/Follower/Followers.jsx
src/Pages/Profile/UserProfile/Profile.jsx
src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
src/Pages/Search/Search.jsx

feat: Profile 페이지 컴포넌트 기능 추가

---

src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx

-
- 현재 더미 데이터를 추가해놓았음
close : #77

feat: UserProduct props 받아서 랜더링하도록 기능추가

---

src/Components/ChatlistProfile.jsx

- 채팅방 리스트 컴퍼넌트로 적용성 확장
-
close : #76

Feat: ChatListProfeile컴퍼넌트생성

---

src/Pages/Register/Register.jsx

design: Register 디자인 수정

---

src/Pages/Page404/Page404.jsx

NotFound404 pages 컴포넌트 생성
-  NotFound404pages 컴포넌트 생성
-
close : #81

feat: NotFound404pages 컴포넌트 생성

---

src/Pages/Chat/ChatRoom/ChatRoom.jsx

ChatRoom 컨포넌트 생성
-
- 채팅룸(미완료) 반대로 나오는 채팅 컴포넌트 생성 후 완료 예정 
close : #85

feat: ChatRoom 컨포넌트 생성

---

src/Components/Navbar/UploadNav.jsx

PostUpload컴포넌트에서도 재사용하기 위함
-
-Upload Nav 사용한 페이지 확인 후 수정 바랍니다
close : #91

feat: UploadNav 컴퍼넌트 prop추가

---

src/Components/TextLogo.jsx

feat: TextLogo 컴포넌트 생성

---

src/Pages/Login/Login.jsx
src/Pages/Login/LoginEmail.jsx
src/Pages/Login/SplashScreen.jsx

feat: login컴포넌트생성

---

src/Components/button/CommonButton.jsx

버튼 텍스트 중앙정렬, 이벤트프롭스 적용, 커서 포인터 적용, 버튼
화이트일때 2px 증가 -> height 값을 주어 변동 없게 수정
버튼 텍스트 중앙정렬
버튼 이벤트 받을수 있는 프롭스 추가
버튼 css 커서 포인터 추가
버튼 bg 화이트 일때 2px 증가 -> height 값으로 고정 
-
close : #88

design: CommonButton CSS 수정

---

src/Components/TabMenu.jsx
src/Components/icon/IconHome.jsx
src/Components/icon/IconMessageCircle.jsx
src/Components/icon/IconUser.jsx
src/Router/Router.jsx

- TabMenu 에 들어가는 아이콘들 병합하였습니다.
- IconHome, IconMessageCircle, IconUser의 Fill 컴포넌트들은 지울예정입니다.
- IconHome, IconMessageCircle, IconUser 아이콘은 각자 접속한 경로에 따라 색이 채워집니다.
close : #99

feat: TabMenu 컴포넌트 link 추가

---

src/Components/Comment.jsx
src/Components/CommonAlert.jsx
src/Components/CommonInput.jsx
src/Components/TextActivInput.jsx
src/Components/UserFollow.jsx
src/Components/UserSerch.jsx

- 다른 컨텐츠들이 컴포넌트를 넘어갈때 비쳐보이지 않음
- Comment 여러 페이지에서 사용 가능
-
close : #89

Design: 세부 컴포넌트 CSS 수정

---

package-lock.json
package.json
src/Pages/Login/LoginEmail.jsx
src/Router/Router.jsx
src/index.js
src/store/Auth.js
src/store/index.js

-LoginEmail 컴포넌트에서 api 테스트 진행
-
close : #102

feat: Redux 설치 및 Store 생성

---

src/Components/ChatlistProfile.jsx

Chatlist 의 profile 사이 간격이 없어 마진추가
-
-
close : #105

design: ChatListProflie CSS 수정

---

src/Pages/Login/LoginEmail.jsx

feat: 로그인 Input 데이터 저장 구현

---

src/Components/Navbar/SearchNav.jsx
src/Components/UserSearch.jsx
src/Pages/Search/Search.jsx

- Search 컴포넌트 검색 기능 구현
- SearchNav 컴포넌트 수정
- UserSearch 컴포넌트 수정
close : #111

feat: Search 컴포넌트 검색 기능 구현

---

src/Components/CommonInput.jsx

form태그 div로 수정
-
-
close : #113

design: Commoninput마크업수정

---

src/Components/ChatRoomChat.jsx

채팅룸에 들어갈 채팅들의 컴퍼넌트 마크업, CSS 디자인
- 채팅 내용, 채팅 시간, 채팅 이미지, 내 채팅과 친구 채팅 일 때의 개별 상황을 따로 받을 수 있도록  프롭스를 부여하여 구현
-
close : #104

feat: ChatRoomChat 컴퍼넌트 생성

---

src/Components/ChatRoomChat.jsx
src/Pages/Chat/ChatList/ChatList.jsx
src/Pages/Chat/ChatRoom/ChatRoom.jsx

-
-ChatRoomChat 컴포넌트 CSS 수정
width 삭제, 폰트 컬러 수정
display, vertical-align 삭제
컴포넌트 함수명 수정
-design: ChatList 컴포넌트 수정
width -> min-widht 수정
padding값 변경
margin-top,position,z-index 추가
-ChatRoom 컴포넌트 수정
마크업 수정, 컴포넌트 나눈 스타일 코드 삭제
ChatRoomContainer 스타일 수정
ChatRoomChat import
profileImg 경로 수정
close : #116

Design: Chat컴포넌트수정

---

src/Components/Modal.jsx
src/Components/icon/IconMoreVerticalSmall.jsx
src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
src/Pages/Post/PostDetail/PostDetail.jsx
src/Router/Router.jsx

feat: PostDetail 데이터요청 및 데이터랜더링

---

src/Components/CommonInput.jsx
src/Pages/Login/LoginEmail.jsx
src/store/UserInfo.js
src/store/index.js

- UserInfo 전역 상태관리로 인한 접근성 향상
- 없음
close : #120

feat: Store에 UserInfo Reducer 추가

---

src/Pages/Login/Login.jsx
src/Pages/Login/LoginEmail.jsx
src/Pages/Post/PostUpload/PostUpload.jsx
src/Pages/SplashScreen/SplashScreen.jsx

style: 코드 컴포넌트화

---

src/Components/button/FileUploadBtn.jsx

feat: FileUploadBtn 컴포넌트 생성

---

src/Pages/Post/PostUpload/PostUpload.jsx

ImgBtn을 FileUploadBtn으로 변경하여  파일 업로드 동작이 가능하게 수정
-
-
close : #126

feat: PostUpload 컴포넌트 수정

---

src/Components/button/CommonButton.jsx

evnet -> event 스펠링 수정
event={event} => onClick={event} 로 수정
-일반 props 에서 onClick={event}함수처리 props로 수정
-
close : #130

design: CommonButton 컴포넌트 이벤트프롭스 설정

---

src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
src/Router/Router.jsx

-  follow,unfollow 버튼 클릭 시 기능 작동
- 없음
close : #132

feat: UserInfo follow,unfollow 기능 추가

---

src/Components/Product.jsx
src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx

- Product 컴포넌트 Props받아서 랜더링
- UserProducts fetch data 및 랜더링
- 없음
close : #134

feat: UserProducts fetch data 및 랜더링

---

src/Pages/Chat/ChatList/ChatList.jsx

feat: Chatlist 컴퍼넌트 Link 기능 추가, 마크업 ul 추가

---

src/Components/ChatlistProfile.jsx
src/Components/Navbar/BasicNav.jsx
src/Components/Navbar/ChatNav.jsx
src/Components/Navbar/MainNav.jsx
src/Components/Navbar/SearchNav.jsx
src/Components/Navbar/UploadNav.jsx
src/Pages/Chat/ChatList/ChatList.jsx

Design: NavBar,ChatListProfile, ChatList컴포넌트수정

---

package-lock.json
package.json
src/store/Profile.js
src/store/UserInfo.js
src/store/index.js

- ProfileReducer 생성 및 userInfo state 변경
- 없음
close : #140

feat: profileReducer 생성 및 userInfo state 변경

---

src/cookie/index.js

- react-cookie 설정 및 setter, getter 함수 설정
- 없음
close : #141

feat: react-cookie 설정 및 setter, getter 함수 설정

---

src/Components/TabMenu.jsx
src/Components/UserSearch.jsx
src/Pages/Login/LoginEmail.jsx
src/Pages/Profile/UserProfile/Profile.jsx
src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
src/Pages/Search/Search.jsx

feat: Profile 컴포넌트에 react-cookie 적용 및 Redux 적용

---

src/Components/Navbar/BasicNav.jsx
src/Components/Navbar/ChatNav.jsx
src/Components/Navbar/SearchNav.jsx
src/Components/Navbar/UploadNav.jsx

feat: Navbar 페이지 이동 기능 구현

---

src/Pages/Profile/UserProfile/EditBtns/EditBtns.jsx
src/Pages/Profile/UserProfile/FollowBtns/FollowBtns.jsx
src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
src/Router/Router.jsx

- EditProfile, EditProduct 경로 추가
- UserInfo컴포넌트 버튼 분리
- UserInfo컴포넌트 버튼 권한별 출력
-
-
close : #152

feat: UserInfo컴포넌트 버튼 권한별 출력

---

src/Components/HomePost.jsx

feat: home post컴포넌트화

---

src/Router/Router.jsx

feat: Router Login path추가

---

src/store/Register.js
src/store/index.js

feat: RegisteredSlice구현

---

src/Pages/Login/LoginEmail.jsx

feat: LoginEmail 기능 구현

---

src/Pages/Register/Register.jsx

feat: Register 회원가입 기능 구현

---

src/Components/CommonInput.jsx

feat: CommonInput props 추가

---

src/App.js
src/Components/Auth/Authentication.jsx
src/Components/icon/IconUser.jsx

- 토큰이 있다면 새로고침 시 유저정보를 다시 받아올 수 있음
- 없음
close : #165

feat: Refresh시 UserInfo 불러오기 기능 추가

---

src/Components/Navbar/MainNav.jsx
src/Components/Navbar/UploadNav.jsx

feat: Navbar Link 수정

---

src/Pages/Login/LoginEmail.jsx

- 더이상 이전 State를 참조하지 않음
- 없음
close : #174

feat: LoginEmail 기능 개선

---

src/Components/button/CommonButton.jsx

disabled 속성을 props 값으로 false true 를 주어 능동적 사용 가능하게 적용
-
-
close : #178

design: CommonButton 컴퍼넌트 disabled 속성 적용

---

src/Pages/SetProfile/SetProfile.jsx
src/store/Register.js

feat: SetProfile 기능구현

---

src/Pages/Post/PostDetail/PostDetail.jsx
src/store/PostDetail.js
src/store/index.js

- PostDetail 컴포넌트 비동기 함수를 Store 로 코드분리
- HomePost로 전달하는 Props 수정
- 없음
close : #183

feat: PostDetail Store사용 및 기능 개선

---

src/Pages/Login/LoginEmail.jsx

- id, pw중 하나라도 입력되어야 버튼 활성
-
close : #180

feat: 로그인 버튼 비활성 기능 구현

---

src/Pages/Home/Home.jsx
src/Pages/Register/Register.jsx

feat: Register 버튼비활성화구현

---

src/Components/DeleteAlert.jsx
src/Components/HomePost.jsx
src/Components/Modal.jsx
src/Components/Navbar/BasicNav.jsx
src/Components/icon/IconMoreVertical.jsx
src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
src/Pages/Post/PostDetail/PostDetail.jsx
src/Pages/Profile/UserProfile/Profile.jsx
src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
src/store/Modal.js
src/store/index.js

- 모달창 추가로 인한 로그아웃 가능
- 포스트 삭제 가능
- 댓글 삭제 가능
-
close : #191

feat: Modal Store 생성 및 Modal 기능 추가

---

src/Components/button/FileUploadBtn.jsx
src/Pages/Post/PostUpload/PostUpload.jsx

feat: PostUpload 사진 파일 추가, 삭제 및 세부 기능 구현

---

src/Components/Navbar/UploadNav.jsx

feat: UploadNav버튼Disabled추가

---

src/Components/UserSearch.jsx
src/Pages/Profile/UserProfile/FollowBtns/FollowBtns.jsx
src/Pages/Search/Search.jsx
src/store/SearchData.js

- Search 컴포넌트 스크롤 페이징 기능 추가
- 검색 시 매칭되는 데이터 하이라이트기능 추가
- 없음
close :  #196

feat: Search 컴포넌트 기능 추가

---

src/Components/Navbar/MainNav.jsx
src/Pages/Profile/Follows/Follows.jsx
src/store/Follow.js

- Document 바닥으로 스크롤 시 Follow,Following 목록 20개를 추가적으로 불러옴
- 중복되는 코드 병합
- 없음
close : #200

feat: Follows Page 중복되는 코드 병합 및 페이징기능추가

---

src/Components/BasicProfileImg.jsx
src/Components/SmallBasicProfile.jsx

- 중복되는 코드 감소
- 해당 컴포넌트를 사용하는 컴포넌트들은 확인 바랍니다.
close : #204

design: Basic Profile 컴포넌트 테두리 0.5px 추가

---

src/Components/Comment.jsx
src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx
src/Pages/Post/PostDetail/PostDetail.jsx
src/store/PostDetail.js

- Post 에 댓글 작성 가능
- 없음
close : #203

feat: Post 댓글 기능 추가

---

src/Components/HomePost.jsx
src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx

- 신고 및 삭제 가능
- 없음
close : #207

feat: Modal 권한별 다른 Modal 보여주기

---

src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx
src/store/Profile.js

Feat: EditUserProfile기능

---

src/Components/CommonInput.jsx
src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx

- 수정 페이지 연결 시 유저가 설정해 놓은 값이 초기 value로 보여지게 됩니다
-
close : #211

Feat: EditUserProfile 유저 설정 값 가져오기

---

src/Pages/Post/PostUpload/PostUpload.jsx

삭제시 input 초기화
-
-
close : #213

feat: PostUpload 이미지 파일 미리보기 삭제 후 재업로드 불가 오류 수정

---

src/Components/Navbar/UploadNav.jsx
src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx

-수정 조건 만족시 버튼 활성화
-
close : #215

Feat: EditUserProfile page disabled기능

---

src/Components/HomePost.jsx
src/Pages/Home/EmptyFeed/EmptyFeed.jsx
src/Pages/Post/PostDetail/PostDetail.jsx
src/store/PostDetail.js

feat: HomePost 하트 토글 및 하트 기능 추가

---

src/Pages/Register/Register.jsx
src/Pages/SetProfile/SetProfile.jsx

-
- 회원가입 완료 시 자동로그인 되어 Feed로 이동
close : #222

feat: 회원가입 API 전송 기능

---

src/Components/Auth/Authentication.jsx
src/Components/Comment.jsx
src/Components/Loader.jsx
src/Components/Navbar/ChatNav.jsx
src/Components/Navbar/SearchNav.jsx
src/Components/UserSearch.jsx
src/Pages/Post/PostDetail/PostDetail.jsx
src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx
src/Pages/Profile/Follows/Follows.jsx
src/Pages/Profile/UserProfile/UserInfo/UserInfo.jsx
src/Pages/Search/Search.jsx
src/store/Profile.js
src/store/UserInfo.js

- 프로필 변경 후 댓글 작성 시 프로필 적용안되는 버그 수정
- 팔로워 페이지에서 NavBar에 옵션 제거
- Loader 폰트 사이즈 조정
- Search 페이지 버그 수정
- 오탈자수정
- 불필요한 콘솔로그 삭제
-
close : #221

fix: 자잘한 버그 수정

---

src/Pages/Profile/EditProfile/EditUserProfile/EditUserProfile.jsx

- UserInfo 다시 받아오기
-
close : #221

feat: UserInfo 다시 받아오기

---

src/Components/Navbar/UploadNav.jsx

feat: UploadNav에 prop으로 onClickUpload 추가

---

src/Pages/SetProfile/SetProfile.jsx

feat: SetProfile 프로필 이미지 업로드 기능

---

src/App.js
src/Components/HomePost.jsx
src/Pages/Home/EmptyFeed/EmptyFeed.jsx
src/Pages/Post/PostDetail/PostDetail.jsx

[fix: 다른 계정 로그인시 UserInfo 재로딩]
[fix: 팔로우 없을 시 검색버튼 활성화]
[fix: React Key 누락 에러 수정]
[design: 크롬브라우저 스크롤 스타일 추가]
[feat: HomePost 여러개 이미지 보여주기 기능 추가]
[feat: 프로필 사진 Link 추가]
[feat: Feed Page Modal 기능 추가]
[feat: Link에 Key 값 추가]
- 없음
close : #227

feat: Home Post 기능추가

---

src/Pages/SetProfile/SetProfile.jsx
src/store/Profile.js

fix: UserProfile Intro 누락 해결

---

src/Components/button/FileUploadBtn.jsx

design: FileUploadBtn hover 디자인 삭제

---

src/Pages/Post/PostUpload/PostUpload.jsx

- Post등록 가능
- 불필요한 x축 스크롤 방지
- 미리보기 이미지 삭제 후 동일 파일 업로드시 업데이트 가능
- y축 스크롤시 프로필 이미지 위치 고정
- textarea 유연한 크기 조절
-
close : #241

feat: PostUpload 기능 및 스타일 수정

---

src/Components/UserFollow.jsx
src/Pages/Post/PostDetail/CommentItem/CommentItem.jsx

- Comment 및 Follow 페이지에서 프로필 사진 클릭 시 이동 기능 추가 
- 없음
close : #248

feat: Comment 및 Follow 페이지 프로필 사진 클릭 시 이동 기능 추가 

---

src/Pages/Profile/UserProfile/Profile.jsx
src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx
src/Pages/SplashScreen/SplashScreen.jsx

feat: 자동로그인처리

---

src/Pages/Profile/Product/AddProduct.jsx
src/Pages/Profile/Product/EditProduct/Editproduct.jsx
src/store/Product.js

Fix: Product detail 수정

---

src/Pages/SetProfile/SetProfile.jsx

- Input을 감싸는 div 태그 -> fieldset으로 변경
-
close : #257

style: SetProfile 기능 스타일 수정

---

src/Pages/Profile/Product/EditProduct/EditProductInput/EditProductInput.jsx
src/Pages/Profile/Product/EditProduct/Editproduct.jsx
src/Pages/Profile/Product/EditProduct/ProductImg/ProductImg.jsx
src/store/Product.js

-코드 가독성 및 유지보수 증가
-
close : #262

Feat/edit product리팩토링

---

src/Pages/Home/EmptyFeed/EmptyFeed.jsx
src/Pages/Profile/UserProfile/Profile.jsx
src/Pages/Search/Search.jsx
src/store/PostList.js

- 무한 스크롤로 인한 데이터 절감 및 사용자 편의성 증가
- 없음
close : #264

feat: Feed 페이지 및 Profile 페이지 무한스크롤 기능추가

---

src/Components/CommonInput.jsx
src/Pages/Login/LoginEmail.jsx

-이메일 입력창 자동 포커스
-
close : #266

feat: Login화면 auto focus 기능 추가

---

src/Pages/Post/PostUpload/PostUpload.jsx

-10MB이상 업로드 시도하면 alert창
-
close : #268

feat: Upload 이미지 파일 용량 제한

---

src/Pages/Login/LoginEmail.jsx
src/Pages/Post/PostUpload/PostUpload.jsx

accent -> light
- 비활성 버튼임을 나타냄
-
close : #270

design: 로그인, 업로드버튼 비활성 색상 수정

---

src/Pages/Post/PostUpload/PostUpload.jsx

- feed페이지로 이동하던 것이 myProfile페이지로 이동
-
close : #272

 feat: PostUpload 후 myProfile페이지로 이동하도록 설정

---

src/Pages/Post/PostUpload/PostUpload.jsx

feat: UploadPost페이지 유저 프로필 사진 설정

---

src/Pages/SetProfile/SetProfile.jsx

feat: SetProfile 버튼 활성화 기능 수정

---

src/Components/HomePost.jsx
src/Components/ImageSlider.jsx
src/Pages/Home/EmptyFeed/EmptyFeed.jsx
src/Pages/Profile/Follows/Follows.jsx
src/Pages/Profile/UserProfile/UserPost/UserPost.jsx
src/Pages/Profile/UserProfile/UserProducts/UserProducts.jsx

- ImageSlider,Follow 컴포넌트 최대 넓이 조정
- EmptyFeed,UserPost 컨테이너 내부 여백 추가
- HomePost 컴포넌트 최대 넓이 조정 및 주석제거
- UserProducts 컴포넌트 Title변경
- 없음
close : #280

design: 페이지별 디자인 세부조정

---

src/Components/button/CommonButton.jsx

- 팔로우 글자 위치 정렬, 경로 오류 해결
-
close : #282

style: CommonButton  글자 위치 수정

---

src/Pages/EditUserProfile/EditUserProfile.jsx

경고창이 떠있어도 submit 되는 상태 수정
- 경고창이 떠있으면 submit 되지 않음
- 프로필 이미지 업로드 때 마다 fetch 실행 -> submit 할 때 fetch 실행으로 수정
-
close : #284

fix: EditUserProfile 유효성 검사 수정

---

src/Components/Chat/ChatListProfile.jsx

border-radius 코드 적용
-
-
close : #288

style: ChatListProfileImg 수정

---

src/Components/Chat/ChatRoomChat.jsx
src/Components/Comment.jsx
src/Pages/Chat/ChatRoom/ChatRoom.jsx

Style: ChatRoom수정

---

src/Pages/AddProduct/AddProduct.jsx
src/Pages/EditUserProfile/EditUserProfile.jsx

-유효성 검사 통과 시 버튼 main 색상으로 수정
-
close : #292

style: Enabled 시, 변경되는 Button 색상 수정

---

src/Components/Auth/Authentication.jsx
src/Pages/Login/Login.jsx
src/Pages/SplashScreen/SplashScreen.jsx

- 불필요한 코드 삭제 및 에러 감소
- 없음
close : #294

fix: Auth관련 에러 수정

---

package-lock.json
package.json
src/api/api.js

-  axios instance 생성
-
close : #297

feat: axios instance 생성

---

src/api/api.js

feat: API 인스턴스생성

---

src/Components/Product.jsx
src/Components/UserFollow.jsx
src/Pages/AddProduct/AddProduct.jsx
src/Pages/LoginEmail/LoginEmail.jsx
src/api/api.js
src/api/auth.js
src/api/post.js
src/api/product.js
src/api/profile.js
src/api/util.js
src/store/Follow.js
src/store/PostDetail.js
src/store/PostList.js

-  axios 마이그레이션으로 인한 코드 중복 감소 및 재사용성 증가
-
close : #

refactor: Follow.js 외 6개 파일 axios 마이그레이션

---

package-lock.json
package.json
src/Components/Product.jsx
src/Pages/AddProduct/AddProduct.jsx
src/Pages/EditProduct/Editproduct.jsx
src/Pages/EditUserProfile/EditUserProfile.jsx
src/Pages/PostDetail/CommentItem/CommentItem.jsx
src/Pages/PostUpload/PostUpload.jsx
src/Pages/Register/Register.jsx
src/Pages/UserProfile/Profile.jsx
src/Pages/UserProfile/UserInfo/UserInfo.jsx
src/api/auth.js
src/api/post.js
src/api/product.js
src/api/profile.js
src/store/Product.js
src/store/ProductList.js
src/store/Profile.js

src\Components\Product.jsx:
src\Pages\AddProduct\AddProduct.jsx:
src\store\PostDetail.js:
src\store\UserInfo.js:
src\Pages\PostUpload\PostUpload.jsx:
src\Pages\Register\Register.jsx:
src\Pages\PostDetail\PostDetail.jsx:
src\Pages\PostDetail\CommentItem\CommentItem.jsx:
src\store\Product.js:
src\store\ProductList.js:
src\store\Profile.js:
- axios 마이그레이션을 통한 코드 중복 감소 및 재사용성 증가
-
close : #302

refactor: PostUpload.jsx 외 10개 파일 axios 마이그레이션

---

src/Components/Comment.jsx
src/Components/HomePost.jsx
src/Pages/Search/Search.jsx
src/Pages/SetProfile/SetProfile.jsx
src/Pages/SplashScreen/SplashScreen.jsx
src/api/comment.js
src/api/homepost.js
src/api/setprofile.js
src/api/splashscreen.js
src/store/SearchData.js
src/store/UserInfo.js

refactor: Comment.jsx 외 6개 파일 axios 마이그레이션

---

package-lock.json
package.json
src/Components/Input/CommonInput.jsx
src/Pages/EditUserProfile/EditUserProfile.jsx
src/Pages/LoginEmail/LoginEmail.jsx
src/api/auth.js
src/api/profile.js
src/constant/regex.js

- React Hook Form 마이그레이션으로 인한 중복코드 제거 및 가독성 향상
- 없음
close : #308

refactor: React Hook Form 마이그레이션 (LoginEmail, EditUserProfile) 

---

src/constant/regex.js

feat: constant/regex 오타 수정

---

package-lock.json
package.json
src/Pages/Register/Register.jsx
src/Pages/SetProfile/SetProfile.jsx
src/api/setprofile.js
src/constant/regex.js

- Hook Form 사용을 통한 코드 중복 감소
- yup 라이브러리를 사용한 이메일, 비밀번호 validation으로 가독성 향상
-
close : #301

refactor: React Hook Form 마이그레이션 (Register, SetProfile) 

---

package-lock.json
package.json
src/index.js
src/util/axeTester.js

- 접근성 향상
- 크롬 개발자 도구를 사용하여 확인 가능
close : #315

feat: 접근성 향상을 위한 @axe-core/react 설치

---

src/Components/Input/CommonInput.jsx

쓰지 않는 porps 및 속성 삭제 input태그에 들어가는 개별적인 속성 option을
사용하여 관리
- input 속성 register 및 option 으로 관리 
- 불필요한 props, input속성 최소화 코드 최적화
-
close : #317

chore: Commoninput 수정

---

src/Components/Navbar/MainNav.jsx
src/Components/TabMenu.jsx
src/Pages/Home/Feed.jsx
src/Pages/Register/Register.jsx
src/Pages/SetProfile/SetProfile.jsx

- axe-core와 개발자도구 lighthouse를 사용한 접근성 개선
-
close : #320

refactor: 시맨틱 마크업

---

src/Components/ImageSlider.jsx
src/Components/Product.jsx
src/Components/TabMenu.jsx
src/Components/UserSearch.jsx
src/Pages/Login/Login.jsx
src/Pages/Search/Search.jsx
src/Pages/UserProfile/Profile.jsx
src/Pages/UserProfile/UserInfo/UserInfo.jsx
src/Pages/UserProfile/UserPost/UserPost.jsx
src/Pages/UserProfile/UserProducts/UserProducts.jsx

시멘틱 마크업으로 인한 접근성 향상
- Login 페이지
- Search 페이지
- UserProfile 페이지
- 없음
close : #319

refactor: 시멘틱 마크업

---

src/Pages/AddProduct/AddProduct.jsx
src/Pages/EditProduct/Editproduct.jsx
src/constant/regex.js
src/util/priceComma.js

Refactor/react hook form 마이그레이션

---

src/Components/Comment.jsx
src/Components/HomePost.jsx
src/Components/ImageSlider.jsx
src/Components/Navbar/UploadNav.jsx
src/Pages/AddProduct/AddProduct.jsx
src/Pages/EditProduct/Editproduct.jsx
src/Pages/EditUserProfile/EditUserProfile.jsx
src/Pages/LoginEmail/LoginEmail.jsx
src/Pages/PostDetail/CommentItem/CommentItem.jsx
src/Pages/PostDetail/PostDetail.jsx

-
- LoginEmail 페이지
- AddProduct, EditUserProfile, Editproduct 페이지
- postDetail 페이지
close : #326

refactor: 시맨틱마크업

---

src/Hooks/useInfinityScroll.jsx
src/Pages/Home/Feed.jsx
src/Pages/UserProfile/Profile.jsx
src/Pages/UserProfile/UserPost/UserPost.jsx
src/store/PostList.js
src/store/SearchData.js

- useInfinityScroll 커스텀 훅을 사용해서 코드 가독성 향상  및 분리
- 사용방법
- 사용할 컴포넌트에서 const [setBottom, pageNum, resetPageNum] = useInfinityScroll() 로 호출
- 최하단 컴포넌트 요소에 <div ref={setBottom}></div> 로 화면에 노출을 감시할 요소를 생성
- pageNum를 통해서 Page 번호를 출력
- resetPageNum 함수를 통해서 Page 번호 1로 초기화
close : #333

feat: 무한스크롤 커스텀 훅 생성 및 적용

---

src/Components/UserSearch.jsx
src/Hooks/useDebounce.jsx
src/Pages/Search/RecentList/RecentList.jsx
src/Pages/Search/Search.jsx
src/Pages/Search/SearchResult/SearchResult.jsx

- useDebounce을 사용해서 코드 가독성 향상
- 없음
close : #335

feat: useDebounce 커스텀 훅 생성 및 적용

---

src/Components/Loader.jsx
src/Pages/Home/Feed.jsx
src/Pages/PostDetail/PostDetail.jsx
src/Pages/UserProfile/Profile.jsx
src/Pages/UserProfile/UserInfo/UserInfo.jsx
src/Pages/UserProfile/UserPost/UserPost.jsx
src/store/PostDetail.js
src/store/PostList.js
src/store/Profile.js

- 페이지가 이동되면서 store의 데이터가 변경될 때 이전 데이터가 출력되는 이슈가 있어서 화면이 업데이트 될 때까지 <Loader> 컴포넌트를 출력하게됨으로써 사용자 경험 증대
- 없음
close : #337

feat: 페이지별 loader 추가

---

src/Components/Navbar/BasicNav.jsx
src/Pages/Home/Feed.jsx
src/store/UserInfo.js

- 무한 로딩 버그수정 및 로그인 버그수정
- 없음
close : #339

fix: 무한 로딩 버그수정 및 로그인 버그수정

---

src/constant/regex.js

fix: 배포 오류 수정 (정규표현식 eslint-disable-next-line 위치 수정)

---

src/router/Router.jsx

- Lazy Import를 통한 코드 스플리팅
- 번들링 크기 분할
- 초기 렌더링 속도 향상 17.4ms => 11.6ms
- 없음
close : #

refactor: rotuer 코드 스플리팅
